# Generated by Django 4.1.6 on 2023-03-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_category_options_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'mt', 'verbose_name_plural': 'It'},
        ),
    ]
