# Generated by Django 4.1.6 on 2023-03-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Category'},
        ),
        migrations.AlterModelOptions(
            name='subcategory2',
            options={'verbose_name_plural': 'Sub Category 2'},
        ),
        migrations.RenameField(
            model_name='subcategory2',
            old_name='category',
            new_name='child',
        ),
        migrations.AddField(
            model_name='subcategory2',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.category'),
            preserve_default=False,
        ),
    ]
