# Generated by Django 4.1.6 on 2023-03-20 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_child_subcategory2_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sub_category2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu.subcategory2'),
        ),
    ]
