# Generated by Django 4.1.6 on 2023-03-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_item_sub_category2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sub_category2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.subcategory2'),
        ),
    ]
