# Generated by Django 4.1.6 on 2023-03-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_item_sub_category2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sub_category2',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.subcategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubCategory2',
        ),
    ]
