# Generated by Django 4.1.6 on 2023-03-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_item_sub_category2_subcategory_category2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='menu.subcategory'),
        ),
    ]
