# Generated by Django 4.1.6 on 2023-03-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
