# Generated by Django 4.1.6 on 2023-03-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_item_category_alter_item_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.subcategory'),
        ),
    ]
