# Generated by Django 4.1.6 on 2023-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_item_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
