# Generated by Django 4.1.6 on 2023-04-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_orders_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sub_category',
        ),
    ]
