# Generated by Django 4.1.6 on 2023-04-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_remove_item_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_pickup',
            field=models.BooleanField(default=True),
        ),
    ]
