# Generated by Django 4.1.6 on 2023-04-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_orders_is_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='is_pickup',
            field=models.IntegerField(choices=[(1, 'Pick-up'), (2, 'Delivery')]),
        ),
    ]
