# Generated by Django 4.1.6 on 2023-04-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_alter_orders_is_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=5),
        ),
    ]
