# Generated by Django 4.1.6 on 2023-04-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_item_quantity_item_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sold',
        ),
    ]
