# Generated by Django 4.1.6 on 2023-04-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_remove_item_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pre_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='pre_order_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
