# Generated by Django 4.1.6 on 2023-04-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_item_pre_order_item_pre_order_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pre_order',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pre_order_limit',
        ),
        migrations.AddField(
            model_name='orders',
            name='pre_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
