# Generated by Django 4.1.6 on 2023-04-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_item_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pre_item',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
