# Generated by Django 4.1.6 on 2023-04-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_item_pre_item_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pre_item',
            field=models.IntegerField(default=0),
        ),
    ]
